config/routes.rb
Rails.application.routes.draw do

  # Root
  root 'posts#index'

  # Post
  get 'flyer' => 'posts#index', as: :index_post
  get 'flyer/new' => 'posts#new', as: :new_post
  post 'flyer/new' => 'posts#create', as: :create_post
  get 'flyer/complete' => 'posts#complete', as: :complete_post
  get 'flyer/category/:category' => 'posts#category', as: :category_post
  get 'flyer/:id' => 'posts#show', as: :show_post

  # Schedule
  get 'schedule' => 'schedules#index', as: :this_schedule
  get 'schedule/:year_month' => 'schedules#index', as: :index_schedule

  # Static
  get 'about' => 'statics#about', as: :about_statics
  get 'terms' => 'statics#terms', as: :terms_statics
  get 'contact' => 'statics#contact', as: :contact_statics

  # Admin
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # API
  mount API => '/'

  # Only Local Env
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Exception
  get '*path', to: 'application#render_404'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :post

  case ENV['RAILS_ENV']
    when "development"
      S3_BUCKET_NAME = 'dev-cdn.artpocket.me'
    when "production"
      S3_BUCKET_NAME = ENV['S3_BUCKET_NAME']
  end

  has_attached_file :image, :styles => {
      :resized => "880x9999>",
    },
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :bucket => S3_BUCKET_NAME,
    :path => "pictures/:style/:id.:extension",
    :url => ":s3_alias_url",
    :s3_host_alias => S3_BUCKET_NAME

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Basic Auth on Development
  if ENV['BASIC_AUTH_USERNAME'] && ENV['BASIC_AUTH_PASSWORD']
    http_basic_authenticate_with :name => ENV['BASIC_AUTH_USERNAME'], :password => ENV['BASIC_AUTH_PASSWORD']
  end

  # Tablet uses PC view
  include Jpmobile::ViewSelector
  before_filter :disable_mobile_view_if_tablet

  def disable_mobile_view_if_tablet
    if request.mobile && request.mobile.tablet?
      disable_mobile_view!
    end
  end

  # Exception
  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def render_404(exception = nil)
    render template: "errors/404", status: 404, layout: 'application'
  end

  def render_500(exception = nil)
    render template: "errors/500", status: 500, layout: 'application'
  end

  # Common Sidebar
  before_filter :sidebar_schedule
  def sidebar_schedule
    today = Time.now.at_beginning_of_day
    tommorow   = today + 1.day
    @today = Post.where("open_date <= ? AND ? <= close_date", today, today).order(close_date: :asc)
    @tommorow = Post.where("open_date = ?", tommorow).order(close_date: :asc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all.order(created_at: :desc).page(1).per(100)
  end

  def category
    @category = Category.find_by(:title => params[:category])
    if @category == nil
      return redirect_to :root
    end
    @posts = Post.where(:category_id => @category.id).order(created_at: :desc).page(1).per(100)
    render :action => 'index'
  end

  def show
    @post = Post.find_by(:id => params[:id])
    if @post == nil
      return redirect_to :root
    end
  end

  def new
    @post = Post.new
    disable_mobile_view!
  end

  def create
    id_hash = SecureRandom.urlsafe_base64(6)

    data = params.require(:post).permit(
        :pictures,
        :title,
        :body,
        :category_id,
        :open_date,
        :close_date,
        :open_time,
        :close_time,
        :place,
        :charge,
        :promoter,
        :url,
        :facebook,
        :twitter,
        :mail
      ).merge(
        :id_hash => id_hash,
      )
    @post = Post.new(data)
    @post.save

    i = 0;
    params[:images].each do |image|
      if image
        @post.pictures.create(:image => image, :priority => i)
        i += 1;
      end
    end

    UserMailer.post_confirm(@post).deliver if ENV['RAILS_ENV']=='development' || ENV['IS_MAILER']=='enable'

    redirect_to complete_post_path(@post.id_hash)
  end

  def complete
    @id_hash = params[:hash_id]
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def index
    set_time = Time.now
    if params[:year_month] != nil
      params[:year_month].match(/^([0-9]{4})([0-9]{2})$/) do |param|
        set_time = Time.mktime(param[1].to_i, param[2].to_i, 01, 00, 00, 00)
      end
    end

    @from = set_time.beginning_of_month
    to = set_time.end_of_month

    @schedules = Post.where("(open_date <= ? AND ? <= close_date)OR(? <= open_date AND close_date <= ?)OR(open_date <= ? AND ? <= close_date)", @from, @from, @from, to, to, to).order(open_date: :asc)

    @size = set_time.at_end_of_month.day
    @calendar = Array.new(@schedules.length){ Array.new(@size) }
    @schedules.each_with_index do |post, i|
      for j in 0..@size do
        day = @from + j.day
        @calendar[i][j] = post.open_date.beginning_of_day <= day.beginning_of_day && day.end_of_day <= post.close_date.end_of_day ? true: false
      end
    end
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'アートポケット',
      separator: '|',
      reverse: true,
      description: '東海のアートイベントのフライヤー紹介サイト',
      keywords: '名古屋, アート, フライヤー',
      canonical: :root,
      og: {
        title: :title,
        type: 'website',
        url: request.original_url,
        image: "http:#{image_url('ogp.png')}",
        site_name: :site,
        description: :description,
        locale: 'ja_JP'
      },
      viewport: 'width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no',
    }
  end

  # params: wday
  # return: japanese day of the week
  def day_ja(w)
    %w(日 月 火 水 木 金 土)[w%7]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="">
<head>
  <%= display_meta_tags(default_meta_tags) %>
  <%= stylesheet_link_tag 'pc/application', media: 'all' %>
  <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
  <%= javascript_include_tag 'pc/application' %>
  <%= analytics_init if Rails.env.production? %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <%= render 'templates/top' %>
  <%= render 'templates/header' %>
  <div class="container">
    <div id="Main" class="main">
      <div class="left">
        <%= yield %>
      </div>
      <%= render 'templates/sidebar' %>
      <i id="mainGoTop" class="gotop icon-up"></i>
    </div>
  </div>
  <%= render 'templates/footer' %>
</body>
</html>

app/views/posts/complete.erb
<h2>投稿完了！</h2>

app/views/posts/index.html.erb
<% set_meta_tags({
title: '新着フライヤー',
og: {
	type: 'website',
},
})%>

<% if !request.smart_phone? %>
	<p class="index_text"><span>NEW</span>イベントカレンダー公開しました。素敵な出会いがありますように。<%= link_to this_schedule_path do %><%= Time.zone.now.strftime("%-m月") %>のカレンダーはこちら<% end %></p>
<% else %>
	<% if @today.present? %>
		<div class="index_schedule">
			<h3 class="index_schedule_title">本日開催中 <%= Time.zone.now.strftime("%-m/%-d") %>(<%= day_ja(Time.zone.now.strftime("%w").to_i) %>)</h3>
			<table class="index_schedule_calendar">
				<% @today.each do |post| %>
					<tr>
						<td>・<%= link_to(truncate(post.title, :length=>18), show_post_path(post.id)) %></td>
						<td>
							<% if post.close_date.strftime("%-m/%-d")==Time.zone.now.strftime("%-m/%-d") %>
								今日まで
							<% elsif post.close_date.strftime("%-m/%-d")==1.days.from_now.strftime("%-m/%-d") %>
								明日まで
							<% else %>
								<%= post.close_date.strftime("%-m/%-d") %>まで
							<% end %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	<% end %>
<% end %>
<div class="post">
	<ul id="IndexList" class="index_list">
		<% @posts.each do |post| %>
			<li>
				<%= link_to show_post_path(post.id) do %>
					<div class="index_list_thumb">
						<%= image_tag(post.pictures[0].image.url(:resized)) %>
					</div>
					<h2 class="index_list_title"><%= truncate(post.title, :length=>35) %></h2>
					<p class="index_list_date">
						<i class="icon-calendar"></i>
						<% if post.open_date!=post.close_date %>
							<%= post.open_date.strftime("%-m/%-d") %>〜<%= post.close_date.strftime("%-m/%-d") %>
						<% else %>
							<%= post.open_date.strftime("%-m/%-d") %>
						<% end %>
						&nbsp;
						<i class="icon-map"></i>
						<%= post.place %>
					</p>
				<% end %>
			</li>
		<% end %>
		<% if request.smart_phone? && @posts.length==1 %>
			<li><a style="background:none;-webkit-box-shadow:none;-moz-box-shadow:none;box-shadow:none;"></a></li>
		<% end %>
	</ul>
	<!-- <p class="index_more">もっと表示する</p> -->

	<script type="text/javascript">
	$(window).load(function() {
		$('#IndexList').masonry({
			itemSelector: 'li',
			<% if request.smart_phone? %>
				columnWidth: (screen.availWidth-10)/2,
			<% else %>
				columnWidth: 300,
			<% end %>
			isFitWidth: true,
	  });
	})
	</script>
</div>

app/views/schedules/index.html.erb
<% set_meta_tags({
title: "#{@from.strftime("%Y年%-m月")}のスケジュール",
og: {
  type: 'website',
},
})%>

<div class="schedule">
<%= link_to index_schedule_path(@from.last_month.strftime("%Y%m")), {:class=>"schedule_prev"} do %>
  <%= @from.last_month.strftime("%Y年%-m月") %>
<% end %>
<%= link_to index_schedule_path(@from.next_month.strftime("%Y%m")), {:class=>"schedule_next"} do %>
  <%= @from.next_month.strftime("%Y年%-m月") %>
<% end %>
  <h2 class="schedule_title"><%= @from.strftime("%Y年%-m月") %>のイベント</h2>
	<table class="schedule_calendar">
    <tr>
      <th></th>
      <% for i in 0...@size do %>
        <th
          <% if @from.days_since(i).strftime("%w").to_i == 0 %>
            class="sunday"
          <% elsif @from.days_since(i).strftime("%w").to_i == 6 %>
            class="saturday"
          <% end %>
        ><%= @from.days_since(i).strftime("%-d") %></th>
      <% end %>
    </tr>
		<tr>
			<th></th>
			<% for i in 0...@size do %>
				<th
          <% if @from.days_since(i).strftime("%w").to_i == 0 %>
            class="sunday"
          <% elsif @from.days_since(i).strftime("%w").to_i == 6 %>
            class="saturday"
          <% end %>
        ><%= day_ja(@from.days_since(i).strftime("%w").to_i) %></th>
			<% end %>
		</tr>
		<% @schedules.each_with_index do |post, i| %>
      <% if i != 0 && i%10 == 0 %>
        <tr>
          <th></th>
          <% for j in 0...@size do %>
            <th
              <% if @from.days_since(j).strftime("%w").to_i == 0 %>
                class="sunday"
              <% elsif @from.days_since(j).strftime("%w").to_i == 6 %>
                class="saturday"
              <% end %>
            ><%= @from.days_since(j).strftime("%-d") %></th>
          <% end %>
        </tr>
        <tr>
          <th></th>
          <% for j in 0...@size do %>
            <th
              <% if @from.days_since(j).strftime("%w").to_i == 0 %>
                class="sunday"
              <% elsif @from.days_since(j).strftime("%w").to_i == 6 %>
                class="saturday"
              <% end %>
            ><%= day_ja(@from.days_since(j).strftime("%w").to_i) %></th>
          <% end %>
        </tr>
      <% end %>
			<tr>
				<td>
          <%= link_to show_post_path(post.id) do %>
            <h3 class="schedule_calendar_title"><%= post.title %></h3>
            <p class="schedule_calendar_date">
              <i class="icon-map"></i>
              <%= post.place %>
              &nbsp;
              <i class="icon-time"></i>
              <%= post.open_time.strftime("%-H:%M") %>〜<%= post.close_time.strftime("%-H:%M") %>
            </p>
          <% end %>
        </td>
				<% for j in 0...@size do %>
					<td
            <% if @from.days_since(j).strftime("%w").to_i == 0 %>
              class="sunday"
            <% elsif @from.days_since(j).strftime("%w").to_i == 6 %>
              class="saturday"
            <% end %>
          ><span class='<%= "enable enable_#{post.category.title}" if @calendar[i][j] %>'></span></td>
				<% end %>
			</tr>
		<% end %>
	</table>
</div>

app/views/schedules/index_smart_phone.html.erb
<% set_meta_tags({
title: "#{@from.strftime("%Y年%-m月")}のスケジュール",
og: {
  type: 'website',
},
})%>

<div class="schedule">
  <%= link_to index_schedule_path(@from.last_month.strftime("%Y%m")), {:class=>"schedule_prev"} do %>
    <%= @from.last_month.strftime("%Y年%-m月") %>
  <% end %>
  <%= link_to index_schedule_path(@from.next_month.strftime("%Y%m")), {:class=>"schedule_next"} do %>
    <%= @from.next_month.strftime("%Y年%-m月") %>
  <% end %>
  <h2 class="schedule_title"><%= @from.strftime("%Y年%-m月") %>のイベント</h2>
  <table class="schedule_calendar">
    <tr>
      <th></th>
      <% for i in 0...@size do %>
        <th
          <% if @from.days_since(i).strftime("%w").to_i == 0 %>
            class="sunday"
          <% elsif @from.days_since(i).strftime("%w").to_i == 6 %>
            class="saturday"
          <% end %>
        ><%= @from.days_since(i).strftime("%-d") %></th>
      <% end %>
    </tr>
    <tr>
      <th></th>
      <% for i in 0...@size do %>
        <th
          <% if @from.days_since(i).strftime("%w").to_i == 0 %>
            class="sunday"
          <% elsif @from.days_since(i).strftime("%w").to_i == 6 %>
            class="saturday"
          <% end %>
        ><%= day_ja(@from.days_since(i).strftime("%w").to_i) %></th>
      <% end %>
    </tr>
    <% @schedules.each_with_index do |post, i| %>
      <% if i != 0 && i%10 == 0 %>
        <tr>
          <th></th>
          <% for j in 0...@size do %>
            <th
              <% if @from.days_since(j).strftime("%w").to_i == 0 %>
                class="sunday"
              <% elsif @from.days_since(j).strftime("%w").to_i == 6 %>
                class="saturday"
              <% end %>
            ><%= @from.days_since(j).strftime("%-d") %></th>
          <% end %>
        </tr>
        <tr>
          <th></th>
          <% for j in 0...@size do %>
            <th
              <% if @from.days_since(j).strftime("%w").to_i == 0 %>
                class="sunday"
              <% elsif @from.days_since(j).strftime("%w").to_i == 6 %>
                class="saturday"
              <% end %>
            ><%= day_ja(@from.days_since(j).strftime("%w").to_i) %></th>
          <% end %>
        </tr>
      <% end %>
      <tr>
        <td>
          <%= link_to show_post_path(post.id) do %>
            <h3 class="schedule_calendar_title"><%= post.title %></h3>
            <p class="schedule_calendar_date">
              <i class="icon-map"></i>
              <%= post.place %>
              &nbsp;
              <i class="icon-time"></i>
              <%= post.open_time.strftime("%-H:%M") %>〜<%= post.close_time.strftime("%-H:%M") %>
            </p>
          <% end %>
        </td>
        <% for j in 0...@size do %>
          <td
            <% if @from.days_since(j).strftime("%w").to_i == 0 %>
              class="sunday"
            <% elsif @from.days_since(j).strftime("%w").to_i == 6 %>
              class="saturday"
            <% end %>
          ><span class='<%= "enable enable_#{post.category.title}" if @calendar[i][j] %>'></span></td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/statics/about.html.erb
<% set_meta_tags({
title: 'このサイトとは',
og: {
  type: 'article',
},
})%>

<div class="static">
  <div class="static_section">
    <h3 class="static_section_title">アートポケットについて</h3>
    <div class="about">
      <p>
        「アートポケット」は、東海のアートイベントの素敵なフライヤーを集めたwebサイト,iOSアプリです。
        「<%= link_to category_post_path(:category=>'graphic') do %>イラスト・グラフィック<% end %>」
        「<%= link_to category_post_path(:category=>'media') do %>写真・映像・メディア<% end %>」
        「<%= link_to category_post_path(:category=>'architecture') do %>建築・インテリア<% end %>」
        「<%= link_to category_post_path(:category=>'fashion') do %>ファッション・クラフト<% end %>」
        「<%= link_to category_post_path(:category=>'graphic') do %>その他<% end %>」
        の5つのカテゴリーに別け、さまざまなジャンルのイベントや展示会が掲載されています。
      </p>
      <p>
        どれだけ素敵な場所や良質な物であっても
        それを伝達しない限り、人に知ってもらうことはできません。
        誰にも知られなければ、どれだけいいものであっても残っていくことができません。
      </p>
      <p>
        アートポケットを通じて、東海のアートイベントをもっと盛んに。
        今までイベントに行ったことがない方には、アートをもっと身近に。
        このサイトを通じて、多くの方が素敵なイベントに出会えるよう願っています。
      </p>
    </div>
  </div>
  <div class="static_section">
    <h3 class="static_section_title">フライヤー掲載について</h3>
    <div class="about">
      <p>
        このサイトへのイベント情報掲載は<strong>完全無料</strong>です。
      </p>
      <p>
        アートポケットwebサイト、iOSアプリ、各種SNSアカウントを用いて宣伝させていただきます。
        イベントHPの代用・告知・集客に、ぜひ当サイトをご利用ください。
      </p>
      <p>
        <%= link_to :terms_statics do %>利用規約<% end %>に同意の上、<%= link_to :new_post do %>フライヤー登録申請<% end %>よりお願いいたします。
      </p>
    </div>
  </div>
  <div class="static_section">
    <h3 class="static_section_title">広告掲載について</h3>
    <div class="about">
      <p>
        イベントの宣伝や作品の販売ページへの誘導など、当サイトの趣旨に沿うものであればバナー広告を掲載する事が出来ます。
      </p>
      <p>
        詳しくは<%= link_to :contact_statics do %>お問い合わせ<% end %>よりご連絡ください。
      </p>
    </div>
  </div>
  <div class="static_section">
    <h3 class="static_section_title">運営について</h3>
    <div class="about">
      <p>
        アートポケットは個人のアートファンからなる数名のチームで運営されており、企業により運営されているものではありません。
      </p>
      <p>
        随時仲間を募集しています。東海のアートシーンをもっと盛り上げたいという熱い想いをお持ちの方、<%= link_to :contact_statics do %>お問い合わせ<% end %>より連絡お待ちしております:)
      </p>
    </div>
  </div>
</div>

app/views/templates/_footer.html.erb
<div class="footer">
  <div class="container">
    <p class="footer_credit">Copyright © Artpocket. All Rights Reserved.</p>
  </div>
</div>

app/views/templates/_header.html.erb
<div id="Header" class="header">
	<div class="container">
		<ul class="header_category">
			<li>
				<%= link_to :root do %>全て<% end %>
			</li>
			<li>
				<%= link_to category_post_path('graphic') do %>
				  <i class="icon-painter graphic"></i> イラスト・グラフィック
				<% end %>
			</li>
			<li>
				<%= link_to category_post_path('media') do %>
					<i class="icon-video digital"></i> 写真・映像・メディア
				<% end %>
			</li>
			<li>
				<%= link_to category_post_path('architecture') do %>
					<i class="icon-home architecture"></i> 建築・インテリア
				<% end %>
			</li>
			<li>
				<%= link_to category_post_path('fashion') do %>
					<i class="icon-tshirt fashion"></i> ファッション・クラフト
				<% end %>
			</li>
			<li>
				<%= link_to category_post_path('other') do %>
					<i class="icon-more other"></i> その他
				<% end %>
			</li>
		</ul>
		<%= link_to this_schedule_path, {:class=>"header_schedule"} do %>
			<span>NEW</span>イベントカレンダー
		<% end %>
	</div>
</div>

app/views/templates/_sidebar.html.erb
<ul class="sidebar">
  <li class="ad">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
         style="display:inline-block;width:300px;height:250px"
         data-ad-client="ca-pub-7183337843978214"
         data-ad-slot="6634443081"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </li>
  <% if @today.present? %>
    <li class="sidebar_schedule">
      <h3 class="sidebar_schedule_title">本日開催中 <%= Time.zone.now.strftime("%-m/%-d") %>(<%= day_ja(Time.zone.now.strftime("%w").to_i) %>)</h3>
      <table class="sidebar_schedule_list">
        <% @today.each do |post| %>
          <tr>
            <td><%= link_to(truncate(post.title, :length=>18), show_post_path(post.id)) %></td>
            <td>
              <% if post.close_date.strftime("%-m/%-d")==Time.zone.now.strftime("%-m/%-d") %>
                今日まで
              <% elsif post.close_date.strftime("%-m/%-d")==1.days.from_now.strftime("%-m/%-d") %>
                明日まで
              <% else %>
                <%= post.close_date.strftime("%-m/%-d") %>まで
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <%= link_to this_schedule_path, {:class=>"sidebar_schedule_link"} do %>
        今月のイベント一覧はこちら
      <% end %>
    </li>
  <% end %>
  <% if @tommorow.present? %>
    <li class="sidebar_schedule">
      <h3 class="sidebar_schedule_title">明日から開催 <%= 1.days.from_now.strftime("%-m/%-d") %>(<%= day_ja(1.days.from_now.strftime("%w").to_i) %>)</h3>
      <table class="sidebar_schedule_list">
        <% @tommorow.each do |post| %>
          <tr>
            <td><%= link_to(truncate(post.title, :length=>18), show_post_path(post.id)) %></td>
            <td><%= post.close_date.strftime("%-m/%-d") %>まで</td>
          </tr>
        <% end %>
      </table>
    </li>
  <% end %>
  <li class="sidebar_fb">
    <iframe        src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fartpocket.me&amp;width=277&amp;height=258&amp;colorscheme=light&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false&amp;appId=705208482920560"
            scrolling="no"
            frameborder="0"
            style="overflow:hidden; width:297px; height:258px;"
            allowTransparency="true">
    </iframe>
  </li>
  <li>
    <a class="twitter-timeline" href="https://twitter.com/artpocket_me" data-widget-id="555687046774153216">@artpocket_meさんのツイート</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </li>
</ul>